set nocompatible
set number
set ruler
set nobackup
set nowritebackup
set noswapfile
set incsearch
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set laststatus=2
set showcmd
set background=dark

syntax enable

" Setup vundle
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

" Plugins
Plugin 'gmarik/vundle'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/syntastic'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()

" Post-vundle
filetype plugin indent on
colorscheme solarized
